### PR TITLE
Add clipboard button

### PR DESCRIPTION
**Pull request by km4**
#21

### CODE REVIEW

**Comment by gavinr** [comment]
@km4 thanks for the PR! I will review shortly.

**Comment by gavinr** [comment]
@km4 thank you again for the PR. A few thoughts:

1. The user does not need to copy the results until the results are shown. So please do not show the button here:

image


2. Can we format the button to use the bootstreap classes and move it to the right to be more consistent?

image

Thanks!

**Comment by km4** [comment]
fine, improve it today :)

**Comment by gavinr** [comment]
Looks great! Thanks!

**Pull request merged**
